### ISSUE TITLE
The published route shows “unpublished” status in the detail page

### ISSUE THREAD

**Issue by nevermosby** [hango-io/ui#1]
I have published a route and it shows correct in the list page, see the details below:

![route-show-wrong-list](https://user-images.githubusercontent.com/1404747/129652239-0b6b190c-e741-45e6-ab3a-9de4d542f5f5.png)

However, the same route shows "unpublished" in the detail page.

![route-show-wrong-detail](https://user-images.githubusercontent.com/1404747/129652498-728b80a0-5a78-4d22-91b0-9883643d88c5.png)

Pls take a look or correct me if it is not a bug.

**Comment by ethanhanjiahao** [comment]
cc @zyao89

**Comment by zyao89** [comment]
https://github.com/hango-io/ui/commit/38e27ed2e4d710779d974d75265301f3c1cc99a2
