### ISSUE TITLE
服务管理-修改，修改服务类型无法生效

### ISSUE THREAD

**Issue by Andy258369** [hango-io/ui#3]
![image](https://user-images.githubusercontent.com/57391635/195008375-85788cfa-0fd2-4804-b6d1-e3f61a42c6be.png)
协议类型切换为dubbo之后，点击保存，该条服务仍是http类型
![image](https://user-images.githubusercontent.com/57391635/195008687-69491958-b144-4b9e-b369-24d5a9377174.png)

**Comment by 1261149215** [comment]
3f4da1e5

**Comment by 1261149215** [comment]
[3f4da1e546afd1b5f27407fbfb0283a0e8c30cca](https://github.com/hango-io/ui/commit/3f4da1e546afd1b5f27407fbfb0283a0e8c30cca)
