### ISSUE TITLE
插件管理-操作列“禁用”，禁用按钮图标看不清

### ISSUE THREAD

**Issue by Andy258369** [hango-io/ui#4]
![image](https://user-images.githubusercontent.com/57391635/195012548-7a14935b-3562-48d8-980a-bed09fabd3ce.png)
![image](https://user-images.githubusercontent.com/57391635/195012583-031efa17-e6b1-4adf-831f-57164183d11c.png)

**Comment by 1261149215** [comment]
commit ID [c22a8e1572820a940db5794ec6adeaec5f4c6f8a](https://github.com/hango-io/ui/commit/c22a8e1572820a940db5794ec6adeaec5f4c6f8a)
