### ISSUE TITLE
服务管理列表页-下拉箭头展开，点击其中一个，本页中所有的下拉都会展开 ,路由管理也是一样的问题

### ISSUE THREAD

**Issue by Andy258369** [hango-io/ui#5]
![image](https://user-images.githubusercontent.com/57391635/195016433-466064f3-ba73-4b99-9b03-72c957ae14c3.png)
![image](https://user-images.githubusercontent.com/57391635/195016454-32c10040-83c8-4941-9582-f4c96f828d20.png)

**Comment by 1261149215** [comment]
commit ID [6a3c351418b1e75c7f964dcd3359485193be2e67](https://github.com/hango-io/ui/commit/6a3c351418b1e75c7f964dcd3359485193be2e67)
